// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReachMobiWebApplication.Data;

#nullable disable

namespace ReachMobiWebApplication.Migrations
{
    [DbContext(typeof(ReachMobiDbContext))]
    [Migration("20230220185921_RenameCollectionIdColumn")]
    partial class RenameCollectionIdColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReachMobiWebApplication.Models.Domain.ClickData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("trackId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ClickData");
                });
#pragma warning restore 612, 618
        }
    }
}
